model:
  base_model: "meta-llama/Llama-3.2-1B-Instruct"
  output_dir: "./policy-chatbot-v1"
  max_seq_length: 512

training:
  num_epochs: 3
  learning_rate: 2e-4
  warmup_ratio: 0.03
  save_steps: 25
  logging_steps: 5
  weight_decay: 0.001
  max_grad_norm: 0.3
  lr_scheduler_type: "cosine"
  save_total_limit: 3
  remove_unused_columns: true
  gradient_checkpointing: true

lora:
  r: 16
  alpha: 32
  dropout: 0.1
  bias: "none"
  task_type: "CAUSAL_LM"

data:
  dataset_path: "../data/document_training_data/training_dataset.jsonl"
  validation_split: 0.0
  max_text_length: 2048
  template_format: "alpaca"

hardware:
  auto_optimize: true
  force_cpu: false
  mixed_precision: "bf16"
  quantization:
    enabled: true
    load_in_4bit: true
    bnb_4bit_quant_type: "nf4"
    bnb_4bit_compute_dtype: "bfloat16"
    bnb_4bit_use_double_quant: true

evaluation:
  run_evaluation: true
  test_questions:
    - "What is the purpose of LINZ's fee waiver policy?"
    - "Who has the authority to waive title fees?"
    - "Can partial title fees be waived?"
    - "What legal authority allows LINZ to waive title fees?"

logging:
  level: "INFO"
  log_to_file: true
  log_hardware_info: true
  log_training_metrics: true
